# CircleCI configuration file
version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: cd App && npm i && npm run test
          name: Run frontend tests
      - run:
          command: cd ../Server && npm i && npm run test
          name: Run backend tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  build_test:
    jobs:
      - build_and_test