version: 2.1

jobs:
  docker:
      - image: circleci/node:10.1.0
  build:
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test 

# # CircleCI configuration file
# version: 2.1
# orbs:
#   node: circleci/node@5.0.2
# jobs:
#   build:
#     executor: node/default # use the default executor defined within the orb
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm
#       - run:
#           command: cd App && npm i
#           name: Build frontend
#       - run:
#           command: cd Server && npm i && npm run build
#           name: Build backend

#   test:
#     executor: node/default # use the default executor defined within the orb
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm
#       - run:
#           command: cd App && npm run test
#           name: Test frontend
#       - run:
#           command: cd Server && npm run test
#           name: Test backend

# workflows:
#   build_test:
#     jobs:
#       - build
#       - test

# version: 2
#   jobs:
#     checkout:
#       docker:
#         - image: circleci/node:11.10
#       working_directory: ~/ci-root
#     steps:
#       - checkout
#       - restore_cache:
#         key: dependency-cache-{{ checksum “package.json” }}
#       - run:
#         name: Install Dependencies
#         command: npm install
#       - save_cache:
#         key: dependency-cache-{{ checksum “package.json” }}
#       paths:
#         - ./node_modules
#         - persist_to_workspace:
#       root: ~/
#       paths:
#         - ci-root
#       test:
#   docker:
#     - image: circleci/node:11.10
#   working_directory: ~/ci-root
#   steps:
#     - attach_workspace:
#       at: ~/
#     - run:
#     name: Install Dependencies
#     command: npm install
# - run: # run tests
# name: Install unit test framework
# command: npm add --save-dev jest-junit
# - run:
# name: Run unit tests
# command: npm run ~/ci-root/node_modules/jest/bin/jest --ci --runInBand --reporters=default --reporters=jest-junit
# environment:
# JEST_JUNIT_OUTPUT: “test-results/jest/results.xml”
# - store_test_results:
# path: test-results
# workflows:
# version: 2
# Continuos Integration:
# jobs:
# - checkout
# - test:
# requires:
# - checkout