

# CircleCI configuration file
version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    executor: node/default # use the default executor defined within the orb
    docker:
      - image: "circleci/node:11.10"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - node/install:
          node-version: "16.17.0"
      - node/install-packages
      - run:
          command: cd App && YELP_API_KEY=${{ secrets.YELP_API_KEY }} npm i
          name: Build frontend
      - run:
          command: cd Server && npm i && YELP_API_KEY=${{ secrets.YELP_API_KEY }} npm run build
          name: Build backend
      - persist_to_workspace:
          root: ~/project
          paths: .
  test:
    executor: node/default # use the default executor defined within the orb
    docker:
      - image: "circleci/node:11.10"
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - node/install-packages:
          pkg-manager: npm
      - node/install:
          node-version: "16.17.0"
      - node/install-packages
      - run:
          command: cd App && YELP_API_KEY=${{ secrets.YELP_API_KEY }} npm run test
          name: Test frontend
      - run:
          command: cd Server && YELP_API_KEY=${{ secrets.YELP_API_KEY }} npm run test
          name: Test backend

workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build